// app/layout.js
import "./globals.css"; // Make sure this file exists and has Tailwind setup
import { ResumeProvider } from './context/ResumeContext';
export const metadata = {
  title: "Resume AI Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&family=Open+Sans&family=Lato&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {/* <div id="resume" className="bg-[#0C1222] p-6 rounded shadow-md">
          {children}
        </div> */}
         <ResumeProvider>
          {children}
        </ResumeProvider>
      </body>
    </html>
  );
}

